const http=require('node:http');const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');
const PORT=process.env.PORT||3000,ROOT=__dirname,DB=path.join(ROOT,'dadras-data.json'),QUESTIONS=path.join(ROOT,'questions.json');
const OPERATORS=new Set(['0910375801','0919619061','0910114803']);
function load(){if(!fs.existsSync(DB)){const d={users:[],activities:[],documents:[],quizzes:[],results:[],messages:[]};fs.writeFileSync(DB,JSON.stringify(d,null,2));return d}return JSON.parse(fs.readFileSync(DB,'utf8'))}let db=load();const save=()=>fs.writeFileSync(DB,JSON.stringify(db,null,2));let bank=JSON.parse(fs.readFileSync(QUESTIONS,'utf8'));
const send=(res,s,b)=>{res.writeHead(s,{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization'});res.end(JSON.stringify(b))};
const read=req=>new Promise((ok,no)=>{let x='';req.on('data',c=>x+=c);req.on('end',()=>{try{ok(x?JSON.parse(x):{})}catch(e){no(e)}})});
const auth=req=>(req.headers.authorization||'').replace(/^Bearer /,'')||null;const user=req=>db.users.find(x=>x.token===auth(req))||null;const operator=req=>{const u=user(req);return u&&u.operator?u:null};const clean=u=>{const {token,...x}=u;return x};const shuffle=a=>[...a].sort(()=>Math.random()-.5);
function publicQuiz(q){return {...q,questionIds:q.questionIds||q.questions||[],questions:undefined}}
function active(q){return !q.publishAt||Date.now()>=new Date(q.publishAt).getTime()}
function getQuestionIds(q){return q.questionIds||q.questions||[]}
function startPayload(q){const ids=getQuestionIds(q);const qs=ids.map(id=>bank.find(x=>x.id===id)).filter(Boolean);const now=Date.now(),duration=Math.max(1,Number(q.durationMin||30));q.attempts=q.attempts||{};return {quizId:q.id,title:q.title,questions:qs.map(x=>({id:x.id,question:x.question,options:x.options})),durationMin:duration,expiresAt:new Date(now+duration*60000).toISOString()}}
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml'};
function serveFile(res,filePath){const ext=path.extname(filePath).toLowerCase();if(!fs.existsSync(filePath)){res.writeHead(404,{'Content-Type':'text/plain; charset=utf-8'});return res.end('Not found')}res.writeHead(200,{'Content-Type':MIME[ext]||'application/octet-stream'});res.end(fs.readFileSync(filePath))}
const server=http.createServer(async(req,res)=>{try{if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization'});return res.end()}const u=new URL(req.url,'http://localhost');
if(req.method==='GET'&&u.pathname==='/'){return serveFile(res,path.join(ROOT,'index.html'))}
if(req.method==='GET'&&(u.pathname==='/dadras.html'||u.pathname==='/dadras'||u.pathname==='/SiteDadras.html')){return serveFile(res,path.join(ROOT,'dadras.html'))}
if(req.method==='GET'&&u.pathname==='/api/health')return send(res,200,{ok:true,bank:bank.length});
if(req.method==='POST'&&u.pathname==='/api/login'){const b=await read(req),nid=String(b.nationalId||'').trim();if(!/^\d{10}$/.test(nid))return send(res,400,{message:'کد ملی باید ۱۰ رقم باشد'});let x=db.users.find(x=>x.nationalId===nid);if(!x){x={id:crypto.randomUUID(),nationalId:nid,operator:OPERATORS.has(nid),name:'کاربر جدید',token:crypto.randomBytes(24).toString('hex'),createdAt:new Date().toISOString()};db.users.push(x)}else{x.token=crypto.randomBytes(24).toString('hex')}save();return send(res,200,{user:{...clean(x),token:x.token}})}
if(req.method==='POST'&&u.pathname==='/api/register'){const b=await read(req),nid=String(b.nationalId||'').trim(),name=String(b.name||'').trim(),phone=String(b.phone||'').trim();if(!/^\d{10}$/.test(nid))return send(res,400,{message:'کد ملی باید ۱۰ رقم باشد'});if(!name)return send(res,400,{message:'نام و نام‌خانوادگی را وارد کنید'});if(!/^\d{10,11}$/.test(phone))return send(res,400,{message:'شماره موبایل معتبر وارد کنید'});let x=db.users.find(x=>x.nationalId===nid);if(x){x.token=crypto.randomBytes(24).toString('hex');if(name)x.name=name;if(phone)x.phone=phone}else{x={id:crypto.randomUUID(),nationalId:nid,name,phone,operator:OPERATORS.has(nid),token:crypto.randomBytes(24).toString('hex'),createdAt:new Date().toISOString()};db.users.push(x)}save();return send(res,201,{user:{...clean(x),token:x.token}})}
if(req.method==='GET'&&u.pathname==='/api/me'){const x=user(req);return x?send(res,200,{user:clean(x)}):send(res,401,{message:'ورود لازم است'})}
if(req.method==='GET'&&u.pathname==='/api/content'){const op=operator(req);const quizzes=db.quizzes.filter(q=>q.type==='fun'||active(q)||op).map(q=>publicQuiz(q));return send(res,200,{activities:db.activities,documents:db.documents,quizzes,results:op?db.results:[],messages:op?db.messages:[]})}
if(req.method==='POST'&&u.pathname==='/api/messages'){const x=user(req);if(!x)return send(res,401,{message:'ابتدا وارد شوید'});const b=await read(req),subject=String(b.subject||'').trim(),message=String(b.message||'').trim();if(!message)return send(res,400,{message:'متن پیام را وارد کنید'});const m={id:crypto.randomUUID(),userId:x.id,nationalId:x.nationalId,subject:subject.slice(0,120),message:message.slice(0,3000),createdAt:new Date().toISOString()};db.messages=db.messages||[];db.messages.unshift(m);save();return send(res,201,{ok:true})}
if(req.method==='DELETE'&&u.pathname.startsWith('/api/messages/')){if(!operator(req))return send(res,403,{message:'فقط اپراتور مجاز است'});db.messages=(db.messages||[]).filter(x=>x.id!==u.pathname.split('/').pop());save();return send(res,200,{ok:true})}
if(req.method==='GET'&&u.pathname==='/api/bank'){if(!operator(req))return send(res,403,{message:'فقط اپراتور مجاز است'});const term=(u.searchParams.get('q')||'').trim().toLowerCase();const questions=bank.filter(q=>!term||q.question.toLowerCase().includes(term)||q.options.some(o=>o.toLowerCase().includes(term))).slice(0,100);return send(res,200,{questions})}
if(req.method==='POST'&&u.pathname==='/api/activities'){if(!operator(req))return send(res,403,{message:'فقط اپراتور مجاز است'});const b=await read(req);const x={id:crypto.randomUUID(),title:String(b.title||''),description:String(b.description||''),date:String(b.date||''),category:String(b.category||''),createdAt:new Date().toISOString()};db.activities.unshift(x);save();return send(res,201,x)}
if(req.method==='DELETE'&&u.pathname.startsWith('/api/activities/')){if(!operator(req))return send(res,403,{message:'فقط اپراتور مجاز است'});db.activities=db.activities.filter(x=>x.id!==u.pathname.split('/').pop());save();return send(res,200,{ok:true})}
if(req.method==='POST'&&u.pathname==='/api/documents'){if(!operator(req))return send(res,403,{message:'فقط اپراتور مجاز است'});const b=await read(req);const x={id:crypto.randomUUID(),name:String(b.name||''),url:String(b.url||''),description:String(b.description||''),createdAt:new Date().toISOString()};db.documents.unshift(x);save();return send(res,201,x)}
if(req.method==='DELETE'&&u.pathname.startsWith('/api/documents/')){if(!operator(req))return send(res,403,{message:'فقط اپراتور مجاز است'});db.documents=db.documents.filter(x=>x.id!==u.pathname.split('/').pop());save();return send(res,200,{ok:true})}
if(req.method==='POST'&&u.pathname==='/api/quizzes'){if(!operator(req))return send(res,403,{message:'فقط اپراتور مجاز است'});const b=await read(req),ids=Array.isArray(b.questionIds)?b.questionIds:[];if(!ids.length)return send(res,400,{message:'حداقل یک سؤال انتخاب کنید'});if(ids.some(id=>!bank.some(q=>q.id===id)))return send(res,400,{message:'یکی از سؤال‌ها در بانک وجود ندارد'});const x={id:crypto.randomUUID(),type:'main',title:String(b.title||'آزمون'),description:String(b.description||''),questionIds:ids,durationMin:Math.min(240,Math.max(1,Number(b.durationMin||30))),publishAt:b.publishAt||null,createdAt:new Date().toISOString()};db.quizzes.unshift(x);save();return send(res,201,publicQuiz(x))}
if(req.method==='POST'&&u.pathname.match(/^\/api\/quizzes\/[^/]+\/start$/)){const x=user(req);if(!x)return send(res,401,{message:'ابتدا وارد شوید'});const id=u.pathname.split('/')[3],q=db.quizzes.find(z=>z.id===id&&z.type!=='fun');if(!q)return send(res,404,{message:'آزمون پیدا نشد'});if(!active(q))return send(res,403,{message:'این آزمون هنوز منتشر نشده است'});const p=startPayload(q);q.attempts=q.attempts||{};q.attempts[x.id]={startedAt:new Date().toISOString(),expiresAt:p.expiresAt};save();return send(res,200,p)}
if(req.method==='POST'&&u.pathname.match(/^\/api\/quizzes\/[^/]+\/finish$/)){const x=user(req);if(!x)return send(res,401,{message:'ابتدا وارد شوید'});const id=u.pathname.split('/')[3],q=db.quizzes.find(z=>z.id===id&&z.type!=='fun');if(!q)return send(res,404,{message:'آزمون پیدا نشد'});const b=await read(req),attempt=q.attempts?.[x.id];if(!attempt)return send(res,400,{message:'این آزمون برای شما شروع نشده است'});const expired=Date.now()>new Date(attempt.expiresAt).getTime();if(expired&&!b.timeout)return send(res,400,{message:'زمان آزمون تمام شده است'});const qs=getQuestionIds(q).map(id=>bank.find(z=>z.id===id)).filter(Boolean),ans=Array.isArray(b.answers)?b.answers:[];let correct=0;const review=qs.map((z,i)=>{const ok=ans[i]===z.correctIndex;if(ok)correct++;return {id:z.id,question:z.question,options:z.options,selected:ans[i]??null,correct:z.correctIndex}});const r={id:crypto.randomUUID(),quizId:q.id,quizTitle:q.title,userId:x.id,nationalId:x.nationalId,correct,total:qs.length,percent:Math.round(correct/qs.length*100),review,createdAt:new Date().toISOString()};db.results.unshift(r);delete q.attempts[x.id];save();return send(res,200,r)}
if(req.method==='POST'&&u.pathname==='/api/fun/start'){const x=user(req);if(!x)return send(res,401,{message:'ابتدا وارد شوید'});if(bank.length<50)return send(res,500,{message:'بانک سؤال کمتر از ۵۰ سؤال دارد'});const qs=shuffle(bank).slice(0,50),id=crypto.randomUUID(),duration=30,expiresAt=new Date(Date.now()+duration*60000).toISOString();db.quizzes.push({id,type:'fun',owner:x.id,questionIds:qs.map(z=>z.id),durationMin:duration,createdAt:new Date().toISOString(),expiresAt});save();return send(res,200,{quizId:id,title:'آزمون تفننی',questions:qs.map(z=>({id:z.id,question:z.question,options:z.options})),durationMin:duration,expiresAt})}
if(req.method==='POST'&&u.pathname==='/api/fun/finish'){const x=user(req);if(!x)return send(res,401,{message:'ابتدا وارد شوید'});const b=await read(req),q=db.quizzes.find(z=>z.id===b.quizId&&z.type==='fun'&&z.owner===x.id);if(!q)return send(res,404,{message:'آزمون پیدا نشد'});const qs=getQuestionIds(q).map(id=>bank.find(z=>z.id===id)).filter(Boolean),ans=Array.isArray(b.answers)?b.answers:[];let correct=0;const review=qs.map((z,i)=>{const ok=ans[i]===z.correctIndex;if(ok)correct++;return {id:z.id,question:z.question,options:z.options,selected:ans[i]??null,correct:z.correctIndex}});const r={id:crypto.randomUUID(),quizId:q.id,quizTitle:'آزمون تفننی',userId:x.id,nationalId:x.nationalId,correct,total:qs.length,percent:Math.round(correct/qs.length*100),review,createdAt:new Date().toISOString()};db.results.unshift(r);save();return send(res,200,r)}
return send(res,404,{message:'Not found'})}catch(e){console.error(e);return send(res,500,{message:'خطای داخلی سرور'})}});server.listen(PORT,'0.0.0.0',()=>console.log(`Dadras listening on 0.0.0.0:${PORT}`));
